import Head from "next/head";
import styles from "../styles/Home.module.css";
import SignIn from "../components/SignIn";
import { useAuth } from "../context/AuthContext";
import Main from "../components/Main";

export default function Home() {
  const { currentUser } = useAuth();
  //console.log("Currentuser",currentUser);
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <SignIn />}
      {currentUser && <Main />}
    </div>
  );
}
